### ISSUE TITLE
Nesting align in gather

### ISSUE THREAD

**Issue by eg9** [latex3/latex2e#15]
## Brief outline of the bug

While the documentation about `amsmath` explicitly mentions that `align` can be nested in `gather` (and there are uses for this), a `\label` in the `align` will raise an error

```! Package amsmath Error: Multiple \label's```

even though the label is correctly written in the `.aux` file and can be referenced.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}

\begin{document}

\begin{gather}
a=b \\
\begin{align}
c&=d+e \\
f&=g+h
\end{align}
\end{gather}

\begin{gather}
a=b \label{A} \\
\begin{align}
c&=d+e \label{B} \\
f&=g+h
\end{align}
\end{gather}

\eqref{A} and \eqref{B}

\end{document}
```

## aux, log and PDF

```latex
\relax 
\newlabel{A}{{4}{1}}
\newlabel{B}{{5}{1}}
```

[gathali.log](https://github.com/latex3/latex2e/files/1673074/gathali.log)

[gathali.pdf](https://github.com/latex3/latex2e/files/1673077/gathali.pdf)

**Comment by blefloch** [comment]
Partial findings: as you know gather typesets twice, align typesets
twice.  For each of them, the first pass is just meant to find sizes of
boxes so \label #1->.  In the second pass, \label checks that it is the
only \label in the line.  This seems to be achieved by storing the label
in \df@label, which is cleared by the \\ in gather (not sure in align).

Now what seems to happen is as follows:

- the first, second and third rows are typeset with \label #1->.
- the second row is re-typeset by align; \df@label->B is not cleared by
\\ because the system in align seems to be different than in gather
- the third row is re-typeset by align;
- adding fourth row after align does not change \df@label since \\ is
defined for the first pass outside align
- then comes the second pass of gather: now it checks \df@label, so in
the first row, \label{A} complains that \df@label->B.

**Comment by eg9** [comment]
Pursuing @blefloch 's idea, if I add
```latex
\global\let\df@label\@empty
```
to the code of `\endalign`, just before `\restorealignstate@` (it's code that's executed only when `\ifingather@` returns true), then the example doesn't raise the spurious error any longer.

The cross references are solved correctly.

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{etoolbox}

\makeatletter
\patchcmd{\endalign}{\restorealignstate@}{\global\let\df@label\@empty\restorealignstate@}{}{}
\makeatother

\begin{document}

\begin{gather}
a=b \\
\begin{align}
c&=d+e \\
f&=g+h
\end{align}
\end{gather}

\begin{gather}
a=b \label{A} \\
\begin{align}
c&=d+e \label{B} \\
f&=g+h
\end{align}
\end{gather}

\begin{align}
c&=d+e \label{C} \\
f&=g+h
\end{align}

\eqref{A} and \eqref{B} and \eqref{C}

\end{document}
```
The aux file
```latex
\relax 
\newlabel{A}{{4}{1}}
\newlabel{B}{{5}{1}}
\newlabel{C}{{7}{1}}
```

**Comment by EigenJacques** [comment]
This is still an issue. 
Encountered when using the following arrangement of nested environments: subequations(gather(align))).
